language: rust
os: osx
rust:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_1fa2432da137_key -iv $encrypted_1fa2432da137_iv
  -in pairing.json.enc -out pairing.json -d
- curl https://krypt.co/kr | sh
- cp pairing.json ~/.kr/pairing.json
- "/usr/local/bin/krd & sleep 2"
- kr team list --admin --pgp | gpg --import
script:
- cargo build --release
- mkdir deploy
- cp target/release/test-verified-deploy deploy/
deploy:
  on:
    branch: master
    condition: '`git verify-commit $TRAVIS_COMMIT && echo success` = "success"'
  local_dir: deploy
  provider: s3
  acl: public_read
  bucket: signed-test.krypt.co
  region: us-east-2
  secret_access_key:
    secure: B+6Iiw859CI2JDLcZE6AHv0Xd4rsDDd87ywDIPvFX0t+MhHozfI6bSJv0dxRfdMremZJc/VzizJK0x8upGTIauTeBqIc2m1QFIBuipaiiR9QaD7wqbSxQrNNHY5bBnnDnjKAamSs27Y8tHb//7UsB1cvcEgRwEuDotvjcfPC6hGsj9He2UeD/GQsUREBYNCib/Jd+ehNfsM5DielJqbGGV/p1C3yd/FaN0k6sZniwGsiQtlq/HYSBIFlp5llUfB7g6GmebezBPJqsGkXABzltznTlJUyKQiVJiK7l9d9Kwdzbe9QjolkIhONNx/FOkBFsma5XdVSkJJLFWfYvmFh6Igr67eECzfk+Blr8tP1dP6DV8/DxQ5NWwaDGhWj45bi/B62EZWuhZB/oAxFFd6WPQxjfB1+I5QO6SnffD+NGV/5Y/jr6korUir6fWHhig+E6v9WXarQYDqztgLon/aKWi01Yzl6VUjpWSFWUKvziCvqiEGhoK5jl5w18J+YvaRbMz+kI88WsiFM15YHFNxtYInaRp7jG3m17+BXULL1Hw1+RYIG5SzGV0ptABbcWcg9r4xbIpQsJMSUfcxPufhsgDGjZR1KkwylERAoYqnFNTB6tiEBt+CasZM/azQ1rSLU7Xqd8oh4NdPx2GlOBAs/KPAHSAPGBIk0wVTpTtD6W+I=
  access_key_id:
    secure: NrkdtoeXLRvNZVISftcP7FxjW1yZdYoJ/ueaWFEIYniZooi/uuS5+GGvjaA52r0T/92iJ6SqPCAHRBVYqamS64bTjBaPO3AYYXO/yiEXny7E9XaOET86fhhIBPE2S4PNiH0mutGfKJQX7qV25yWN4EpKjKcwJsNdjw3vfRo6mMqawmM2jvW9DzPPyU3P0CWBEVI9hZ5ncE+QERjQsuGKd4oMZHEuPBHYb+ZJ6RUNj2iVV+4iHFF52ZJ6be6Jx4H1MFeAoa/nyaZTt5S/T7pxsLjwzz9lC8+KlI7UFQWzHnDazE9e8M4nDBeCtxWGnaZeXdnpaqnm2+xPhRD26qE9Xnl/T/7jdodDX60JGVJ+DdRlgOoBv76eRfp5GhDkMTddiRH4vvOcPxhlHKst+U2sFV/+9TY35oCBaBQ5JuOsowp+/MMpC9JIklbLBgVxdKpIf6XwTa0j1Y/2HGilIcwmZb9XB/BWyFV9lfQ5XF8/Tp9om7Jr+p9yHjLjhJsCm/b/lYHRsaZQRPaJ7+sIwOxieGxxbtj5AFt5DI99TlX4UlP1pNVtDprzjcADta4WAt+C7lIxgwNbMcNzlz2vGOye939dzQg6coY/wFrBjhB+PDHv13NsETWSkM1QrmSyqeJTa22y8ay3co7kxxhyfhtczT1lClYrZlm0cXjacFJHNN0=
